GET https://blog-api-server.onrender.com/

###

POST https://blog-api-server.onrender.com/
Content-Type: application/json

{
  "data": "hello world"
}

###
// two comments
GET https://blog-api-server.onrender.com/blog/63532a4d919aadef64a7666b

###
// one comment
GET https://blog-api-server.onrender.com/blog/63532a4d919aadef64a76669